action: ''
debug: False
timeout: 30
flush: False
state: present
chain: ''
chain_management: False
policy: ACCEPT
target: ''
rule_number: ''
description: ''
source_net4: ''
destination_net4: ''
source_mac_address: ''
protocol: numeric
# protocol
protocol_number: ''
# protocol
source_port: ''
destination_port: ''
#   tcp flags
tcp_flag_syn: any
tcp_flag_ack: any
tcp_flag_fin: any
tcp_flag_rst: any
tcp_flag_urg: any
tcp_flag_psh: any
# protocol
source_udp_port: ''
destination_udp_port: ''
to_ports: ''
# protocol
icmp_type: any
input_interface: any
output_interface: any
fragments: all_packets_and_fragments
reverse_match_for_source_ip_mask: 'no'
reverse_match_for_destination_ip_mask: 'no' 
reverse_match_for_source_mac_address: 'no'
reverse_match_for_source_port: 'no'
reverse_match_for_destination_port: 'no'
reverse_match_for_protocol: 'no'
reverse_match_for_tcp_flags: 'no'
reverse_match_for_icmp_type: 'no'
reverse_match_for_input_interface: 'no'
reverse_match_for_output_interface: 'no'
enable_state_match: 'no'
new: 'no'
established: 'no'
related: 'no'
invalid: 'no'
snat: 'no'
dnat: 'no'
reverse_state_match: 'no'
to_source: ''
to_destination: ''
log_level: 'debug'
log_pefix: ''
log_tcp_sequence_numbers: 'no'
log_options_from_the_tcp_packet_header: 'no'
log_options_from_the_ip_packet_header: 'no'

