- name: Update System Services
  tags: always
  zpe.nodegrid.services:
    services:
      enable_detection_of_usb_devices: "{{ enable_detection_of_usb_devices }}"
      enable_rpc: "{{ enable_rpc }}"
      enable_grpc: "{{ enable_grpc }}"
      enable_ftp_service: "{{ enable_ftp_service }}"
      enable_snmp_service: "{{ enable_snmp_service }}"
      enable_telnet_service_to_nodegrid: "{{ enable_telnet_service_to_nodegrid }}"
      enable_telnet_service_to_managed_devices: "{{ enable_telnet_service_to_managed_devices }}"
      enable_icmp_echo_reply: "{{ enable_icmp_echo_reply }}"
      enable_icmp_secure_redirects: "{{ enable_icmp_secure_redirects }}"
      enable_usb_over_ip: "{{ enable_usb_over_ip }}"
      enable_search_engine: "{{ enable_search_engine }}"
      enable_dashboards: "{{ enable_dashboards }}"
      enable_telegraf: "{{ enable_telegraf }}"
      enable_services_status_page: "{{ enable_services_status_page }}"
      enable_reboot_on_services_status_page: "{{ enable_reboot_on_services_status_page }}"
      enable_vmware_manager: "{{ enable_vmware_manager }}"
      enable_docker: "{{ enable_docker }}"
      enable_qemu|kvm: "{{ enable_qemu }}"
      cluster_tcp_port: "{{ cluster_tcp_port }}"
      auto_cluster_enroll: "{{ auto_cluster_enroll }}"
      search_engine_tcp_port: "{{ search_engine_tcp_port }}"
      enable_search_engine_high_level_cipher_suite: "{{ enable_search_engine_high_level_cipher_suite }}"
      enable_vm_serial_access: "{{ enable_vm_serial_access }}"
      vm_serial_port: "{{ vm_serial_port }}"
      vmotion_timeout: "{{ vmotion_timeout }}"
      enable_zero_touch_provisioning: "{{ enable_zero_touch_provisioning }}"
      enable_bluetooth: "{{ enable_bluetooth }}"
      enable_pxe: "{{ enable_pxe }}"
      device_access_per_user_group_authorization: "{{ device_access_per_user_group_authorization }}"
      enable_autodiscovery: "{{ enable_autodiscovery }}"
      dhcp_lease_per_autodiscovery_rules: "{{ dhcp_lease_per_autodiscovery_rules }}"
      block_host_with_multiple_authentication_fails: "{{ block_host_with_multiple_authentication_fails }}"
      period_host_will_stay_blocked: "{{ period_host_will_stay_blocked }}"
      timeframe_to_monitor_authentication_fails: "{{ timeframe_to_monitor_authentication_fails }}"
      number_of_authentication_fails_to_block_host: "{{ number_of_authentication_fails_to_block_host }}"
      allow_root_console_access: "{{ allow_root_console_access }}"
      rescue_mode_require_authentication: "{{ rescue_mode_require_authentication }}"
      password_protected_boot: "{{ password_protected_boot }}"
      ssh_allow_root_access: "{{ ssh_allow_root_access }}"
      ssh_tcp_port: "{{ ssh_tcp_port }}"
      ssh_ciphers: "{{ ssh_ciphers }}"
      ssh_macs: "{{ ssh_macs }}"
      ssh_kexalgorithms: "{{ ssh_kexalgorithms }}"
      enable_http_access: "{{ enable_http_access }}"
      http_port: "{{ http_port }}"
      enable_https_access: "{{ enable_https_access }}"
      https_port: "{{ https_port }}"
      redirect_http_to_https: "{{ redirect_http_to_https }}"
      enable_https_file_repository: "{{ enable_https_file_repository }}"
      frr_enable_bgp: "{{ frr_enable_bgp }}"
      frr_enable_ospfv2: "{{ frr_enable_ospfv2 }}"
      frr_enable_ospfv3: "{{ frr_enable_ospfv3 }}"
      frr_enable_rip: "{{ frr_enable_rip }}"
      frr_enable_vrrp: "{{ frr_enable_vrrp }}"
      tlsv1.3: "{{ tlsv1_3 }}"
      tlsv1.2: "{{ tlsv1_2 }}"
      tlsv1.1: "{{ tlsv1_1 }}"
      tlsv1: "{{ tlsv1 }}"
      cipher_suite_level: "{{ cipher_suite_level }}"
